### ISSUE TITLE
Upload not work

### ISSUE THREAD

**Issue by zell180** [somenonymous/OshiUpload#17]
From Yesterday upload not work on oshi.at
Can you help me?

**Comment by zell180** [comment]
Problem still occurr

**Comment by somenonymous** [comment]
`oshi.at` has been constantly attacked lately (DDoS and abuse reports) which made us switching frontend server providers and some of them weren't of good quality. This situation will normalize soon once we find a decent frontend server provider for our service.

However, our backend server is not affected by this and is always reachable via .onion link: http://5ety7tpkim5me6eszuwcje7bmy25pbtrjtue7zkqqgziljwqy3rrikqd.onion

**Comment by somenonymous** [comment]
`oshi.at` has been constantly attacked lately (DDoS and abuse reports) which made us switching frontend server providers and some of them weren't of good quality. This situation will normalize soon once we find a decent frontend server provider for our service.

However, our backend server is not affected by this and is always reachable via .onion link: http://5ety7tpkim5me6eszuwcje7bmy25pbtrjtue7zkqqgziljwqy3rrikqd.onion

**Comment by somenonymous** [comment]
`oshi.at` has been constantly attacked lately (DDoS and abuse reports) which made us switching frontend server providers and some of them weren't of good quality. This situation will normalize soon once we find a decent frontend server provider for our service.

However, our backend server is not affected by this and is always reachable via .onion link: http://5ety7tpkim5me6eszuwcje7bmy25pbtrjtue7zkqqgziljwqy3rrikqd.onion
