### ISSUE TITLE
Error thene running ./oshi_run.pl

### ISSUE THREAD

**Issue by HkopMD** [somenonymous/OshiUpload#2]
I have followed the guide but this error com then I run ./oshi_run.pl

Can't locate Short/URL.pm in @INC (you may need to install the Short::URL module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at ./functions.pm line 9.
BEGIN failed--compilation aborted at ./functions.pm line 9.
Compilation failed in require at ./oshi_run.pl line 11.

**Comment by marcovelon** [comment]
`Short::URL` module seem to be not installed on your system. This module is not in Debian packages and should be installed separately. The easiest way is to install it from `cpan`, so this command should work: 

`cpan -i Short::URL`

**Comment by HkopMD** [comment]
Ooh thanks I will try that

**Comment by somenonymous** [comment]
Next release will include Short::URL to avoid confusion with this module when using perl modules from the OS distribution.
