### ISSUE TITLE
Accessing oshi.at using HTTPie is very slow on macOS

### ISSUE THREAD

**Issue by amotl** [somenonymous/OshiUpload#22]
Dear @somenonymous,

while working on GH-21, we discovered that, while accessing oshi.at using `curl` works perfectly on all platforms [^1], and there also seem to be no issues when using Linux, it shows a significant delay when using [HTTPie] on macOS.

### macOS
It can easily be validated by running:
```sh
{brew,pip} install httpie
```

```sh
time http https://oshi.at/
real	1m16.628s
user	0m0.307s
sys	0m0.077s
```

### Linux
```sh
docker run -it --rm debian:bullseye-slim bash
apt update
apt-get install --yes httpie
```
```sh
time http https://oshi.at/
real	0m0.364s
user	0m0.192s
sys	0m0.023s
```

Do you by chance run any kind of OS fingerprinting on oshi.at, which might classify the signature of macOS of something bad, where it would add a delay on purpose? Or, do you have any other suggestions why this happens, maybe it's just me?

With kind regards,
Andreas.

[HTTPie]: https://httpie.io/

[^1]: `curl https://oshi.at/`

**Comment by somenonymous** [comment]
Hi, there is no way we would employ such malicious practices on our instance. We certainly don't use any fingerprinting techniques on it nor have any other logs enabled that would permit sorting users based on their metadata, therefore this problem seem to be directly related to MacOS.

Please debug it at your side.

**Comment by amotl** [comment]
Thanks for your swift reply. Let me close this issue then. I will re-open it again when I might be able to reproduce it more reliably.
