### ISSUE TITLE
PUT request with destroy-after-download + expiry 7d?

### ISSUE THREAD

**Issue by retorquere** [somenonymous/OshiUpload#3]
What URL should I use to get a file with 7d expiry and destroy after download?

**Comment by somenonymous** [comment]
It seems currently there is no possibility to do that. Next commit will cover that case.

**Comment by somenonymous** [comment]
It's now possible with the following requests:

`curl -T /path/to/file "https://oshi.at/?autodestroy=1&expire=10080"` 
or 
`curl -T /path/to/file https://oshi.at/file/10080?autodestroy=1` 
or 
`curl -T /path/to/file https://oshi.at/file/-1?expire=10080` 

Check https://oshi.at/cmd for updated information.
