### ISSUE TITLE
Update Tor site http://oshiatwowvdbshka.onion/ for https://oshi.at (URGENT)

### ISSUE THREAD

**Issue by RaidenMK** [somenonymous/OshiUpload#4]
Hi.
This is not an issue,its more of a question for you. 
There is no email to send to you,so I'll post it here.. Could you please update the site http://oshiatwowvdbshka.onion/ to v3? It will end soon. check out: https://support.torproject.org/onionservices/v2-deprecation/

**Comment by somenonymous** [comment]
Thanks for bringing it into concern, the onion address will be migrated to v3 soon.

**Comment by somenonymous** [comment]
The current onion address is `5ety7tpkim5me6eszuwcje7bmy25pbtrjtue7zkqqgziljwqy3rrikqd.onion`, however we may add yet another address within next weeks.
