### ISSUE TITLE
Upload Stuck at 100%

### ISSUE THREAD

**Issue by Sushrut1101** [somenonymous/OshiUpload#8]
I've tried uploading a large file (3.8GB) to oshi.at but the upload is stuck at 100%.

The Command I ran is:
```bash
curl https://oshi.at -F f=@out/file.zip -F shorturl=0
```

But the upload is stuck at 100%

Any Help Please?

**Comment by Sushrut1101** [comment]
> I've tried uploading a large file (3.8GB) to oshi.at but the upload is stuck at 100%.
> 
> The Command I ran is:
> 
> ```shell
> curl https://oshi.at -F f=@out/file.zip -F shorturl=0
> ```
> 
> But the upload is stuck at 100%
> 
> Any Help Please?

I also tried using curl -T but same result :(

**Comment by marcovelon** [comment]
Service seems to work fine. Check for possible network issues on your side, i.e. if your DNS provider isn't trying to block this domain. Are you able to upload via website?

**Comment by marcovelon** [comment]
Service seems to work fine. Check for possible network issues on your side, i.e. if your DNS provider isn't trying to block this domain. Are you able to upload via website?

**Comment by Sushrut1101** [comment]
> It's more likely your ISP doing shady business, try using .onion site or VPN.

It's working fine on small files.
Is there any file size limit?

**Comment by somenonymous** [comment]
The actual file size limit is which is shown on the main web page, it's 5GB currently.

Can you tell what time takes sending that 3.8GB file from your system? I guess it could be some timeout at one of our servers then. Reopening this for now.
